# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-03-22 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='標題')),
                ('content', models.CharField(max_length=200, verbose_name='內容')),
            ],
        ),
    ]
